# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='El nombre con el que nos referiremos al nodo en la plataforma', max_length=128, unique=True, verbose_name='Nombre del nodo')),
                ('creation_date', models.DateField(blank=True, editable=False, null=True)),
                ('place', models.CharField(blank=True, help_text='El nombre de la localidad —ciudad, pueblo, ámbito— donde se ubica el nodo.', max_length=128, null=True, verbose_name='Localidad')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('image', models.ImageField(blank=True, help_text='Sube una imagen representativa del nodo: un logo, una foto...', upload_to='images/projects/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, help_text='Una descripción corta de la actividad del nodo. Se usará de resumen en el perfil del nodo.', verbose_name='Descripción')),
                ('geom', djgeojson.fields.PointField(help_text='Añade la ubicación del nodo. Usa el buscador en la esquina superior derecha para localizar una dirección. Has de usar el nombre exacto para que éste funcione correctamente.', null=True, verbose_name='Ubicación')),
                ('members', models.PositiveIntegerField(default=1, help_text='Cuánta gente trabaja en el nodo.', verbose_name='Número de miembros')),
                ('manager', models.ForeignKey(help_text='El usuario que crea el nodo es el manager por defecto del mismo. Puedes cambiarlo posteriormente editando el nodo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
                ('users', models.ManyToManyField(help_text="Especifica aquí a usuari-s de la red que pertenecen a este Proyecto. Mantén presionado 'Control' o 'Command' en un Mac, para seleccionar más de una opción.", related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del proyecto')),
            ],
        ),
    ]
