# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Node',
        ),
    ]
