# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 12:51
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0003_auto_20170612_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='El titulo del post.', max_length=128, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('creation_date', models.DateField(default=datetime.date.today, help_text='Usa el formato dd/mm/aaaa, por ejemplo: 01/05/2015.', verbose_name='Fecha')),
                ('image', models.ImageField(blank=True, help_text='Una imagen representativa para las vistas de contenido y para la cabecera de la vista del post completo.', upload_to='images/blog/', verbose_name='Imagen')),
                ('summary', models.TextField(blank=True, help_text='Un resumen de la noticia para las vistas de contenidos, si no lo usas se usará un recorte del cuerpo.', verbose_name='Resumen')),
                ('wysiwyg', ckeditor_uploader.fields.RichTextUploadingField(help_text='El texto completo de la noticia.', verbose_name='Texto')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor-')),
            ],
        ),
    ]
