# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Especifica aquí a usuari-s de la red que pertenecen a este Proyecto. Mantén presionado 'Control' o 'Command' en un Mac, para seleccionar más de una opción.", related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del proyecto'),
        ),
    ]
