# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20170618_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True, help_text='Sólo los contenidos publicados serán visibles. Desmarca esta casilla para generar un borrador que podrás publicar más adelante, cuando esté acabado.', verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='node',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='El usuario que crea el nodo es el manager por defecto del mismo. Puedes cambiarlo posteriormente editando el nodo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador'),
        ),
    ]
