# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20170618_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Un título significativo para el documento.', max_length=128, verbose_name='Título')),
                ('creation_date', models.DateField(editable=False)),
                ('category', models.CharField(choices=[('PU', 'Cesión de entidad pública a colectivo'), ('PR', 'Cesión de entidad privada a colectivo'), ('CO', 'Cesión de colectivo a colectivo')], default='me', help_text='Entre qué entidades se ha firmado el acuerdo.', max_length=2, verbose_name='Tipo de acuerdo')),
                ('summary', models.TextField(help_text='Resume en uno o dos párrafos el contenido del acuerdo.', verbose_name='Resumen')),
                ('language', models.CharField(choices=[('ES', 'Español'), ('CA', 'Catalán'), ('GA', 'Gallego'), ('EU', 'Euskera'), ('EN', 'Inglés'), ('FR', 'Francés')], default='ES', help_text='¿En qué idioma en que está redactado el documento? Si crees necesario añadir algún idioma contacta con nosotras.', max_length=2, verbose_name='Idioma')),
                ('document', models.FileField(help_text='Adjunta el documento en PDF o ODT preferentemente.', upload_to='documents', verbose_name='Documento')),
            ],
        ),
    ]
