# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la referencia.', max_length=128, verbose_name='Título')),
                ('summary', models.TextField(help_text='Resume en uno o dos párrafos la referencia.', verbose_name='Resumen')),
                ('image', models.ImageField(blank=True, help_text='Una imagen representativa de la referencia.', upload_to='images/blog/', verbose_name='Imagen')),
                ('link', models.URLField(help_text='Enlace para ampliar la información sobre la referencia', verbose_name='Enlace')),
            ],
        ),
        migrations.AlterField(
            model_name='agreement',
            name='language',
            field=models.CharField(choices=[('ES', 'Español'), ('CA', 'Catalán'), ('GA', 'Gallego'), ('EU', 'Euskera'), ('EN', 'Inglés'), ('FR', 'Francés'), ('OT', 'Otros')], default='ES', help_text='¿En qué idioma en que está redactado el documento? Si crees necesario añadir algún idioma contacta con nosotras.', max_length=2, verbose_name='Idioma'),
        ),
    ]
