# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:49
from __future__ import unicode_literals

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20170621_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ponle un nombre significativo al reuso.', max_length=128, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('published', models.BooleanField(default=True, help_text='Sólo los contenidos publicados serán visibles. Desmarca esta casilla para generar un borrador que podrás publicar más adelante, cuando esté acabado.', verbose_name='Publicado')),
                ('date', models.DateField(default=datetime.date.today, help_text='Usa el formato dd/mm/aaaa, por ejemplo: 01/05/2015.', verbose_name='Fecha del reuso')),
                ('image', models.ImageField(help_text='Una imagen significativa del reuso para las vistas de resúmenes de contenido y el encabezado de la vista completa. Puedes añadir más imágenes al texto completo del reuso.', upload_to='images/news/', verbose_name='Imagen')),
                ('wysiwyg', ckeditor_uploader.fields.RichTextUploadingField(help_text='Cuerpo de texto del reuso.', verbose_name='Texto completo')),
                ('summary', models.TextField(help_text='Un resumen de la noticia para las vistas de contenidos, si no lo usas se usará un recorte del cuerpo.', verbose_name='Resumen')),
                ('place', models.CharField(blank=True, help_text='El nombre de la localidad —ciudad, pueblo, ámbito— donde se hizo el reuso. Aunque es opcional, esta información ayuda al resto de usuari@s a contextualizar la iniciativa rápidamente.', max_length=128, null=True, verbose_name='Localidad')),
                ('address', models.CharField(blank=True, help_text='Dirección del nodo. No es necesario que incluyas la localidad anterior.', max_length=128, null=True, verbose_name='Dirección')),
                ('geom', djgeojson.fields.PointField(help_text='¿Dónde se hizo el reuso?', null=True, verbose_name='Ubicación')),
                ('agreement', models.ManyToManyField(blank=True, help_text='Puedes asociar documentos de acuerdos de cesión al reuso.', related_name='agreement', to='models.Agreement', verbose_name='Acuerdos')),
                ('nodes', models.ManyToManyField(help_text="¿Qué nodos de la red han participado en el reuso? Mantén presionado 'Control' o 'Command' en un Mac, para seleccionar más de una opción.", related_name='Nodos', to='models.Node', verbose_name='Nodos')),
            ],
        ),
    ]
