# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_reuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(blank=True, choices=[('UD', 'Unidades'), ('ML', 'Metros lineales'), ('M2', 'Metros cuadrados'), ('M3', 'Metros cúbicos')], default='Unidades', help_text='Especifica la unidad a usar cuando se cuantifica este material.', max_length=2, verbose_name='Unidad'),
        ),
    ]
