# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('models', '0012_auto_20170622_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, editable=False)),
                ('category', models.CharField(choices=[('me', 'Quiero mandar un mensaje genérico'), ('of', 'Quiero notificar al nodo que tengo materiales que puede querer'), ('de', 'Tengo interés en materiales de este nodo')], default='me', help_text='Elige el tipo de mensaje que quieres enviar.', max_length=2, verbose_name='Tipo de mensaje')),
                ('body', models.TextField(help_text='Texto del mensaje. No está permitido usar HTML. Las URLs se convertirán directamente en enlaces.', verbose_name='Mensaje')),
                ('author', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('emissor', models.ForeignKey(blank=True, help_text='Especifica el proyecto que quieres que aparezca como remitente. Esto es aconsejado si el mensaje se manda en relación a un lote.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to='models.Node', verbose_name='Remitente')),
                ('receiver', models.ForeignKey(help_text='Nodo al que envias el mensaje', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='models.Node', verbose_name='Destinatario')),
            ],
        ),
    ]
