# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_auto_20170624_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reuse',
            new_name='Space',
        ),
    ]
