# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 10:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_auto_20170625_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='wysiwyg',
        ),
        migrations.AddField(
            model_name='space',
            name='reuse',
            field=models.BooleanField(default=True, help_text='¿Es el espacio el escenario de un reuso?', verbose_name='¿Es un reuso'),
        ),
        migrations.AlterField(
            model_name='space',
            name='agreement',
            field=models.ManyToManyField(blank=True, help_text='Puedes asociar documentos de acuerdos de cesión al espacio.', related_name='agreement', to='models.Agreement', verbose_name='Acuerdos'),
        ),
        migrations.AlterField(
            model_name='space',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Usa el formato dd/mm/aaaa, por ejemplo: 01/05/2015.', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='space',
            name='geom',
            field=djgeojson.fields.PointField(help_text="Usa el botón inferior para localizar el espacio a partir de los valores de los campos anteriores, 'Localidad' y 'Dirección'.", null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ImageField(help_text='Una imagen significativa del espacio para las vistas de resúmenes de contenido y el encabezado de la vista completa. Puedes añadir más imágenes al texto completo del reuso.', upload_to='images/news/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(help_text='Ponle un nombre significativo al espacio.', max_length=128, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='space',
            name='nodes',
            field=models.ManyToManyField(help_text="¿Qué nodos de la red participan en este espacio? Mantén presionado 'Control' o 'Command' en un Mac, para seleccionar más de una opción.", related_name='Nodos', to='models.Node', verbose_name='Nodos'),
        ),
        migrations.AlterField(
            model_name='space',
            name='published',
            field=models.BooleanField(default=True, help_text="Sólo los contenidos 'publicados' son visibles. Desmarca esta casilla para generar un contenido provisional que podrás hacer público más adelante.", verbose_name='Publicado'),
        ),
    ]
