# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_auto_20170625_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='date',
        ),
        migrations.AddField(
            model_name='space',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de alta en la plataforma'),
        ),
    ]
