# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_auto_20170625_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/batches/', verbose_name='Imagen')),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad total de material en el lote, medido en las unidades del material', null=True, verbose_name='Cantidad total')),
                ('offered', models.PositiveIntegerField(help_text='¿Cuánto se ofrece de la cantidad total?', verbose_name='Cantidad ofrecida')),
                ('public_info', models.TextField(blank=True, help_text='Información sobre este lote, visible de manera pública', null=True, verbose_name='Información pública')),
                ('private_info', models.TextField(blank=True, help_text='Información sobre el lote, sólo visible para usuari-s de los nodos asociados al espacio', null=True, verbose_name='Información privada')),
                ('expiration', models.DateField(blank=True, help_text='Fecha límite para acceder a la ofera asociada, en caso de que la haya. Usa el formato dd/mm/aaaa, por ejemplo: 01/05/2015.', null=True, verbose_name='Fecha de expiración')),
                ('material', models.ForeignKey(help_text='El material del que se compone el lote', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Material', verbose_name='Tipo')),
                ('space', models.ForeignKey(help_text='¿En qué espacio está este lote?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Espacio')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
