# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 19:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_auto_20170625_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='offered',
        ),
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.CharField(choices=[('of', 'Oferta de materiales'), ('de', 'Demanda de materiales')], default='de', help_text='¿Ofreces o necesitas materiales?', max_length=2, verbose_name='¿Oferta o demanda?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration',
            field=models.DateField(blank=True, help_text='Fecha de caducidad para la oferta/demanda.', null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='¿Cuánto se oferta o necesita? Medido en las unidades del material.', null=True, verbose_name='Cantidad ofrecida'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='space',
            field=models.ForeignKey(help_text='¿A qué espacio está asociada la oferta/demanda?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='post',
            name='grrr_blog',
            field=models.BooleanField(default=False, help_text='Indica si es un post para el blog principal de la web.', verbose_name='Blog del GRRR'),
        ),
        migrations.AlterField(
            model_name='space',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Fecha de alta en la plataforma'),
        ),
    ]
