# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_auto_20170625_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='expiration',
            field=models.DateField(blank=True, help_text='Fecha límite opcional para la oferta/demanda.', null=True, verbose_name='Fecha de expiración'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='private_info',
            field=models.TextField(blank=True, help_text='Información de carácter privado, sólo para usuari*s de los nodos asociados al espacio.', null=True, verbose_name='Información privada'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='public_info',
            field=models.TextField(blank=True, help_text='Informa en este campo de características del lote.', null=True, verbose_name='Información pública'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Especifica en las unidades del material cuánto se ofrece o necesita —opcional—.', null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Batch'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space'),
        ),
    ]
