# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_auto_20170707_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='milestones',
            field=models.ManyToManyField(to='models.Milestone'),
        ),
    ]
