# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_auto_20170707_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='activated',
        ),
        migrations.AddField(
            model_name='milestone',
            name='category',
            field=models.CharField(choices=[('AC', 'Materiales activados'), ('TR', 'Materiales transferidos')], default='TR', max_length=2),
        ),
        migrations.AddField(
            model_name='milestone',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
