# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 16:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_auto_20170707_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Fecha de entrada del lote en tu inventario', verbose_name='Fecha de entrada'),
        ),
    ]
