# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_auto_20170707_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='total',
            field=models.PositiveIntegerField(blank=True, help_text='Especifica en las unidades del material cuánta cantidad hay en total en el lote.', null=True, verbose_name='Cantidad total'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Especifica en las unidades del material cuánto se ofrece/necesita (opcional en este último caso).', null=True, verbose_name='Cantidad'),
        ),
    ]
