# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_auto_20170707_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='category',
        ),
        migrations.AddField(
            model_name='sms',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Si mandas el mensaje en relación a una oferta/demanda puedes especificarla aquí.', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Batch', verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='sms',
            name='reply',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Sms'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='emissor',
            field=models.ForeignKey(blank=True, help_text='Si escribes en nombre de un espacio puedes especificarlo aquí.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to='models.Space', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='receiver',
            field=models.ForeignKey(help_text='Espacio al que envias el mensaje', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='models.Space', verbose_name='Destinatario'),
        ),
    ]
