# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_auto_20170709_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sms',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
