# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_auto_20170710_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sms',
            name='date',
        ),
        migrations.AddField(
            model_name='sms',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 7, 10, 13, 8, 20, 594314)),
        ),
        migrations.AlterField(
            model_name='batch',
            name='space',
            field=models.ForeignKey(help_text='¿Qué espacio ofrece o demanda?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Espacio'),
        ),
    ]
