# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_auto_20170710_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
