# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_auto_20170710_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='actived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Especifica en las unidades del material cuánto se ofrece o necesita (opcional en este último caso).', null=True, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='total',
            field=models.PositiveIntegerField(blank=True, help_text='En caso de lotes de oferta puedes especificar aquí una cantidad total mayor a la ofertada si se da el caso.', null=True, verbose_name='Cantidad total'),
        ),
        migrations.AlterField(
            model_name='post',
            name='grrr_blog',
            field=models.BooleanField(default=False, help_text='Indica si es un post del equipo editorial. La selección de espacio se ignora si marcas esta opción.', verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, help_text='¿Al blog de qué espacio está asociado este post?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='emissor',
            field=models.ForeignKey(blank=True, help_text='Especifica el espacio al que representas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emissor', to='models.Space', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='space',
            name='place',
            field=models.CharField(help_text='El nombre de la localidad —ciudad, pueblo, ámbito— donde se sitúa el espacio.', max_length=128, null=True, verbose_name='Localidad'),
        ),
    ]
