# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_auto_20170711_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='actived',
        ),
        migrations.AlterField(
            model_name='batch',
            name='category',
            field=models.CharField(choices=[('of', 'Oferta de materiales'), ('de', 'Demanda de materiales'), ('ac', 'Lote activado')], default='de', help_text='¿Ofreces o necesitas materiales?', max_length=2, verbose_name='¿Oferta o demanda?'),
        ),
    ]
