# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_auto_20170711_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='weight',
            field=models.FloatField(blank=True, help_text='Especifica el peso por unidad en kilogramos de manera aproximada. Se usará para hacer cálculos de materiales recuperados y puestos en uso', null=True, verbose_name='Peso unitario'),
        ),
    ]
