# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_auto_20170712_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='target',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='models.Space', verbose_name='Objectivo'),
        ),
    ]
