# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0039_batch_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='category',
        ),
        migrations.RemoveField(
            model_name='milestone',
            name='quantity',
        ),
    ]
