# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_auto_20170712_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='category',
            field=models.CharField(choices=[('of', 'Oferta de materiales'), ('de', 'Demanda de materiales'), ('ac', 'Lote activado'), ('re', 'Lote recuperado')], default='of', help_text='¿Ofreces o necesitas materiales?', max_length=2, verbose_name='¿Oferta o demanda?'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='models.Space', verbose_name='Objectivo'),
        ),
    ]
