# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 10:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0041_auto_20170712_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='grrr_blog',
        ),
        migrations.AlterField(
            model_name='batch',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text="Fecha de entrada del lote en tu inventario. Usa el formato dd/mm/aaaa, por ejemplo '01/05/2015' para el 1 de Mayo de 2015.", verbose_name='Fecha de entrada'),
        ),
        migrations.AlterField(
            model_name='node',
            name='users',
            field=models.ManyToManyField(blank=True, help_text="Especifica aquí a usuari-s de la red que pertenecen a este Proyecto. Mantén presionado 'Control' o 'Command' en un Mac, para deseleccionar o seleccionar más de una opción.", related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios del proyecto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, help_text='¿A qué blog está asociado este post?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Si mandas el mensaje en relación a una oferta/demanda puedes especificarla aquí.', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Batch', verbose_name='Lote relacionado'),
        ),
        migrations.AlterField(
            model_name='space',
            name='agreement',
            field=models.ManyToManyField(blank=True, help_text="Puedes asociar documentos de acuerdos de cesión al espacio. Mantén presionado 'Control' o 'Command' en un Mac, para deseleccionar o seleccionar más de una opción.", related_name='agreement', to='models.Agreement', verbose_name='Acuerdos'),
        ),
        migrations.AlterField(
            model_name='space',
            name='nodes',
            field=models.ManyToManyField(help_text="¿Qué colectivos de la red participan en este espacio? Mantén presionado 'Control' o 'Command' en un Mac, para deseleccionar o seleccionar más de una opción.", related_name='spaces', to='models.Node', verbose_name='Nodos'),
        ),
        migrations.AlterField(
            model_name='space',
            name='summary',
            field=models.TextField(help_text='Describe brevemente el espacio y su actividad. Puedes usar el blog del espacio para ampliar la información sobre el mismo.', verbose_name='Resumen'),
        ),
    ]
