# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_auto_20170715_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, help_text='¿A qué blog está asociado este post?', null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Space', verbose_name='Blog'),
        ),
    ]
