# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0043_auto_20170805_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='url',
            field=models.URLField(blank=True, help_text='Dirección opcional para ampliar información sobre este colectivo.', null=True, verbose_name='Enlace'),
        ),
    ]
