# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0042_auto_20170714_1325'),
        ('models', '0044_node_url'),
    ]

    operations = [
    ]
