# Generated by Django 2.2.12 on 2020-04-21 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0046_auto_20171107_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='space',
            field=models.ForeignKey(help_text='¿Qué espacio ofrece o demanda?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Space', verbose_name='Espacio'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source', to='models.Space', verbose_name='Objectivo'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Space'),
        ),
        migrations.AlterField(
            model_name='node',
            name='geom',
            field=djgeojson.fields.PointField(help_text='Añade la ubicación del nodo.', null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='node',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='El usuario que crea el nodo es el manager por defecto del mismo. Puedes cambiarlo posteriormente editando el nodo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Autor-'),
        ),
        migrations.AlterField(
            model_name='post',
            name='space',
            field=models.ForeignKey(blank=True, help_text='¿A qué blog está asociado este post?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Space', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sms',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Si mandas el mensaje en relación a una oferta/demanda puedes especificarla aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Batch', verbose_name='Lote relacionado'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='emissor',
            field=models.ForeignKey(blank=True, help_text='Especifica el espacio al que representas.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emissor', to='models.Space', verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='receiver',
            field=models.ForeignKey(help_text='Espacio al que envias el mensaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to='models.Space', verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='replies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Sms'),
        ),
        migrations.AlterField(
            model_name='space',
            name='geom',
            field=djgeojson.fields.PointField(help_text='Añade la ubicación del nodo.', null=True, verbose_name='Ubicación'),
        ),
    ]
