# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_message_seen_date',
            field=models.DateTimeField(),
        ),
    ]
