# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170710_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_message_seen_date',
            new_name='last_message_seen_datetime',
        ),
    ]
