# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170710_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_message_seen_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
